title: Adam Wright
tagline: Distributed Postgres, Security, and Kubernetes
description: >-
  Notes on distributed databases, security, and Kubernetes from Adam Wright,
  Product Manager for EDB Postgres Distributed (PGD).
url: "https://theadamwright.github.io"
author:
  name: Adam Wright

plugins:
  - jekyll-seo-tag
  - jekyll-feed

markdown: kramdown

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
